// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fauqdhzevoczslqkoqgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhdXFkaHpldm9jenNscWtvcWdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTMxNjUsImV4cCI6MjA1Nzk2OTE2NX0.dnDnRlB9-9wDv5DukjwwtQmHS2V9xQf3_tZdJDIJT6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);